### PR TITLE
Add support for filename-pattern on ns-group

### LINKED ISSUE #1790: Support `:file-pattern` on `:ns-group`
**Is your feature request related to a problem? Please describe.**
At Nubank, we want to use the `discouraged-var` linter only on test namespaces, the issue is that we can know for sure a ns is in a test source-path only checking the `ns`, we need to check the source-path.

**Describe the solution you'd like**
if we support a `:file-pattern` on the `:ns-group` we would be able to exclude specific source-paths.

**Describe alternatives you've considered**
no alternatives AFAICS

**Additional context**
https://clojurians.slack.com/archives/CHY97NXE2/p1661880291392359

I can help with a PR

### PR DESCRIPTION
**Pull request by ericdallo**
Fixes #1790

Please answer the following questions and leave the below in as part of your PR.

- [X] I have read the [developer documentation](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md).

- [X] This PR corresponds to an [issue with a clear problem statement](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).

- [X] This PR contains a [test](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md#tests) to prevent against future regressions

- [X] I have updated the [CHANGELOG.md](https://github.com/clj-kondo/clj-kondo/blob/master/CHANGELOG.md) file with a description of the addressed issue.

### CODE REVIEW

**Comment by borkdude** [comment]
Looks good, I wonder if this works on Windows too using the same regex.

**Comment by ericdallo** [comment]
@borkdude good catch, maybe I can simplify the regex

**Comment by borkdude** [comment]
Isn't that just hiding the problem? I think those regexes should work for *nix and Windows, else you would have to write some pretty hairy regexes to target both. We already have similar regexes for `:output {:exclude-file ...}`.

**Comment by borkdude** [comment]
Hmm, since we don't have support for this in `:exclude-files` either, we will address that when necessary. So this PR is sufficient imo.

**Pull request merged**
