### PR TITLE
Analyse types of do and doto expressions

### PR DESCRIPTION
**Pull request by yuhan0**
I found these changes that I made some time ago while poking around the type analyzer, figured they would be useful :)

- [x] I have read the [Clojure etiquette](https://clojure.org/community/etiquette) and will respect it when communicating on this platform.

- [x] I have read the [developer documentation](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md).

- [ ] This PR corresponds to an [issue with a clear problem statement](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).

- [x] This PR contains a [test](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md#tests) to prevent against future regressions

- [ ] I have updated the [CHANGELOG.md](https://github.com/clj-kondo/clj-kondo/blob/master/CHANGELOG.md) file with a description of the addressed issue.

### CODE REVIEW

**Comment by NoahTheDuke** [comment]
The "regression" comes from the deliberate discarded value in [read-discard](https://github.com/clojure/tools.reader/blob/0d3a7cd946e0ef377b7fe2c85df6cf940ff39c81/src/main/clojure/clojure/tools/reader/edn.clj#L299-L302):

```clojure
(defn- read-discard
  [rdr _ opts]
  (doto rdr
    (read true nil true)))
```

**Comment by yuhan0** [comment]
That's a strange one... I shrunk it down to this minimal repro:

```clj
(ns clojure.tools.reader.edn
  (:refer-clojure :exclude [read]))

(declare read)
(doto nil (read))
```
The "unused value" warning only appears when the ns is specifically `clojure.tools.reader.edn`, changing it to any other name causes it to go away. Maybe something to do with the cache? The actual `read` function defined below does lots of side-effecting things like throwing exceptions, but somehow the analyser is treating it as a pure one.

Which also brings up the question, should this be marked with an unused-value warning:

`(doto 1 (inc))`

The master branch does not, but this PR analyses the doto 'more accurately', allowing the analyser to see that the pure function `inc` is being used in an unreachable position.

Not sure how to continue debugging from here

**Comment by yuhan0** [comment]
Note that `(doto 1 inc inc)` produces a warning on the master branch, the difference is that the analyser now appends the `1` at the end of the doto expansion so it recognizes the first `inc` as being unused.



Maybe it's reasonable to assume that every function call in a `doto` is there for side-effecting reasons (that the user 'knows what they're doing')? 

Either way it seems unrelated to the PR.. here's a command line version of the above repro

```bash
$ echo '(ns clojure.tools.reader.edn) (declare read) (doto nil (read))' | ./clj-kondo --lint -
<stdin>:1:56: warning: Unused value
linting took 9ms, errors: 0, warnings: 1
```

For some reason I could not reproduce it within a deftest, eg. this passes:

```clj
(deftest weird-test
  (assert-submaps ()
   (lint!
    "(ns clojure.tools.reader.edn) (declare read) (doto nil (read))"
    {:linters {:unused-value {:level :warning}
               :type-mismatch {:level :warning}}})))
```

**Comment by borkdude** [comment]
I thought it might be related to this one: https://github.com/clj-kondo/clj-kondo/pull/2334/files/eb75edc95d1f4be2ebb1a0432d66c70f66ee56b2#diff-f591b825c81f488c7fa9426a07ba9dd30f948cc52e445be929d5fd8299bc7dde

but I'd have to take a look.

With clj-kondo master I get:

```
$ echo '(ns clojure.tools.reader.edn) (declare read) (doto nil (read))' | clj-kondo --lint -
linting took 42ms, errors: 0, warnings: 0
```

> Either way it seems unrelated to the PR

That seems a bold claim since it doesn't occur without this PR ;)

**Comment by borkdude** [comment]
What issue number does this PR correspond to btw? Maybe it's better to split the PR up into two parts. The one for `do` which seems trivial and then another one for `doto` on top of that.

**Comment by yuhan0** [comment]
Here's the false positive observed on the master branch:

```clj
(do
  (require '[clojure.tools.reader.edn :as ctr.edn])
  (ctr.edn/read) ;; <--
  :ok)
```

```bash
$ echo '(do (require \'[clojure.tools.reader.edn :as ctr.edn]) (ctr.edn/read) :ok)' | clj-kondo --lint  -
<stdin>:1:55: warning: Unused value
linting took 9ms, errors: 0, warnings: 1
```

There isn't a corresponding issue for this PR, do you need one to be opened?

**Comment by borkdude** [comment]
Alright, since there isn't an issue corresponding to this PR, changes aren't thought through properly (relying on me to guess why things have changed), etc, I'm inclined to close this PR. Feel free to create separate issues for each problem that was identified and optionally a PR.

**Comment by yuhan0** [comment]
Sure, sorry about that - will open corresponding issues later for these.

**Comment by borkdude** [comment]
No problem, I just find that easier to track/reason about. Thanks for the help!

**Comment by borkdude** [comment]
I found the issue with clojure.tools.reader.edn/read:

https://github.com/jonase/eastwood/issues/451

**Comment by borkdude** [comment]
Submitted separate PRs for do and doto, which fixes all of the above issues and made @yuhan0 co-author since he already wrote most of the code already in this PR.

**Pull request closed without merging**
