### PR TITLE
[analysis] Add output-schema-str to analysis output for schema.core

### PR DESCRIPTION
**Pull request by ericdallo**
Fixes https://github.com/clj-kondo/clj-kondo/issues/1268

Related to https://github.com/clojure-lsp/clojure-lsp/issues/181

- Add `output-schema-str` to `var-definitions` for `schema.core/def` and `schema.core/defn` (the only two possible output schemas var definitions).

I thought about `output-schemas-str` but it seems an unnecessary optimization for now as `schema.core` only allows one output schema per var.

### CODE REVIEW

**Comment by borkdude** [comment]
This seems a bit of an ad hoc solution which only applies to the schema library. I would like to see an issue and some discussion first before we go ahead with this.

**Comment by ericdallo** [comment]
@borkdude do you see any other better solution for this?

**Comment by borkdude** [comment]
My last comment still stands.

**Comment by borkdude** [comment]
Closing this due to staleness.

**Comment by ericdallo** [comment]
I think this is still a good idea, but I have other priorities and didn't have the time to get this one, maybe leave it open still?

**Comment by ericdallo** [comment]
oh, the issue is relevant, the PR can be closed indeed

**Pull request closed without merging**
