### PR TITLE
Update docs and messaging around imported configs

### LINKED ISSUE #1697: Imported Configs are now Automatically Activated
## Version
`v2022.04.25`

## Platform
All

## Problem
Docs and messaging around imported configs are a bit stale.
It is no longer necessary to specify imported configs in `:config-paths` if the import config conforms the suggested structure.

## Repro
In a new empty dir, given the following `deps.edn`
```Clojure
{:deps {clj-kondo/config {:git/url "https://github.com/clj-kondo/config"
                          :sha "c37c13ea09b6aaf23db3a7a9a0574f422bb0b4c2"}}}
```
Run:
```
$ mkdir .clj-kondo
$ clj-kondo --copy-configs --dependencies --lint "$(clojure -Spath)"
Imported config to .clj-kondo/clj-kondo/better-cond. To activate, add "clj-kondo/better-cond" to :config-paths in .clj-kondo/config.edn.
Imported config to .clj-kondo/clj-kondo/claypoole. To activate, add "clj-kondo/claypoole" to :config-paths in .clj-kondo/config.edn.
Imported config to .clj-kondo/clj-kondo/mockery. To activate, add "clj-kondo/mockery" to :config-paths in .clj-kondo/config.edn.
Imported config to .clj-kondo/clj-kondo/rum. To activate, add "clj-kondo/rum" to :config-paths in .clj-kondo/config.edn.
Imported config to .clj-kondo/clj-kondo/slingshot. To activate, add "clj-kondo/slingshot" to :config-paths in .clj-kondo/config.edn.
```

## Proposals
Happy to discuss, just initial ideas:

### Messaging
Proposal for new messaging:

```
Active imported configs:
- .clj-kondo/clj-kondo/better-cond. 
- .clj-kondo/clj-kondo/claypoole. 
- .clj-kondo/clj-kondo/mockery. 
- .clj-kondo/clj-kondo/rum. 
- .clj-kondo/clj-kondo/slingshot.
```

When none found, no message is displayed.

### Handling of existing/new/modified
We are currently only showing new configs where a new config is one that is not already specified in `:config-paths`.  

Option 1: show all active import configs (current proposal)
Option 2: show all active import configs but mark new/changed ones
Option 3: show only new/changed import configs
Option 4: ?

### Handling of configured :config-paths
Since we are focused on imported configs, I propose that we report on what is found in the file system and not look at anything that might happen to be in `config.edn` `:config-paths`.

### Docs
Config docs should be updated to match new messaging and behavior.

## Next Steps
After we agree on an approach, I am happy to follow up with a PR.

### PR DESCRIPTION
**Pull request by lread**
Closes #1697

Please answer the following questions and leave the below in as part of your PR.

- [x] I have read the [developer documentation](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md).

- [x] This PR corresponds to an [issue with a clear problem statement](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).

- [x] This PR contains a [test](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md#tests) to prevent against future regressions

- [x] I have updated the [CHANGELOG.md](https://github.com/clj-kondo/clj-kondo/blob/master/CHANGELOG.md) file with a description of the addressed issue.

### CODE REVIEW

**Comment by lread** [comment]
Two thoughts:
- `inactive-config-test` could be renamed to `copied-config-test` or merged into existing `copy-config-test` (thought review diff would be easier if I waited on this one).
- should we recommend `--skip-lint` instead of `--dependencies` in docs, or is it fine the way it is?

**Comment by borkdude** [comment]
@lread It's slightly subtle.

To ensure that while linting dependencies (with `--dependencies`), the right configs are already in place, you can do an initial:

```
clj-kondo --lint $(clojure -Spath) --copy-configs --skip-lint
```

Then after that you can lint dependencies for better linting information:

```
clj-kondo --lint $(clojure -Spath) --dependencies --parallel
```

And then finally, you can lint your own project:

```
clj-kondo --lint src:test
```

I'm surprised to see code changes in the way how configs are copied. This issue is only about updating messaging right?

**Comment by lread** [comment]
> I'm surprised to see code changes in the way how configs are copied. This issue is only about updating messaging right?

Yup. Should be no changes to code that copies. 
Only changes to areas that report on those copies.

**Comment by borkdude** [comment]
@lread I have trouble seeing what these changes have to do with only changes to error reporting :)

Screenshot 2022-05-17 at 20 52 23

**Comment by lread** [comment]
I'm glad you asked. 🙂 

So we used to report only on inactive configs.
These were the copied configs that were not already specified in `:config-paths`.

But now things are simpler, we just report on all copied configs.

**Comment by borkdude** [comment]
Gotcha!

**Comment by lread** [comment]
I'm still thinking this is a good idea. Watcha think @borkdude?

> * `inactive-config-test` could be renamed to `copied-config-test` or merged into existing `copy-config-test` (thought review diff would be easier if I waited on this one).

**Comment by borkdude** [comment]
I agree! We should also document this part:

https://github.com/clj-kondo/clj-kondo/pull/1698#issuecomment-1129202561

**Pull request merged**
