### PR TITLE
Issue 426 warning for a loop without a recur

### PR DESCRIPTION
**Pull request by drewverlee**
This request should solve issue #426 , though there might be some minor clean-up (I store more in the atom than necessary, names, code organization) that should be considered before accepting it. But it's probably worth getting some feedback before I try doing any of that. 

The solution must include a stack or at least a pseudo stack so that nested loops are handled correctly. 

My primary worry is the logic is very disjoint, but given the nature of the problem that might be unavoidable. 

Here is the output from running the diff script. I'm not entirely sure what it's telling me:

```
➜  clj-kondo git:(issue-426-warning-for-a-loop-without-a-recur) ✗ ./script/diff
Linting and writing output to /tmp/clj-kondo-diff/branch.txt
Cloning into 'clj-kondo'...
remote: Enumerating objects: 12375, done.
remote: Counting objects: 100% (1399/1399), done.
remote: Compressing objects: 100% (598/598), done.
remote: Total 12375 (delta 764), reused 1173 (delta 696), pack-reused 10976
Receiving objects: 100% (12375/12375), 11.82 MiB | 44.18 MiB/s, done.
Resolving deltas: 100% (7145/7145), done.
Linting and writing output to /tmp/clj-kondo-diff/master.txt
DEPRECATED: Libs must be qualified, change refactor-nrepl => refactor-nrepl/refactor-nrepl (/home/drewverlee/.clojure/deps.edn)
1923c1923
< clojure/tools/reader.clj:18:53: warning: use alias or :refer [char desugar-meta ex-info? namespace-keys numeric? reader-conditional second' tagged-literal whitespace?]
---
> clojure/tools/reader.clj:18:53: warning: use alias or :refer [char desugar-meta ex-info? namespace-keys numeric? second' whitespace?]
2173c2173
< inlined/clj_kondo/impl/toolsreader/v1v2v2/clojure/tools/reader.clj:16:87: warning: use alias or :refer [char desugar-meta ex-info? namespace-keys numeric? reader-conditional second' tagged-literal whitespace?]
---
> inlined/clj_kondo/impl/toolsreader/v1v2v2/clojure/tools/reader.clj:16:87: warning: use alias or :refer [char desugar-meta ex-info? namespace-keys numeric? second' whitespace?]
2558c2558
< linting took 8622ms, errors: 264, warnings: 2293
---
> linting took 8732ms, errors: 264, warnings: 2293
```

### CODE REVIEW

**Comment by borkdude** [comment]
> The solution must include a stack or at least a pseudo stack so that nested loops are handled correctly.

That mechanism works automatically when you just insert an atom into the context and then analyze. The next time you encounter a fn or loop another atom is inserted so by the time you will encounter a recur, it automatically corresponds to the closest fn/loop: no need to build more stack-like logic.

**Comment by drewverlee** [comment]
@borkdude 

> it automatically corresponds to the closest fn/loop: 

yes, but if it inserts a new atom on each loop then it forgets the past/parents. What if they still need a matching recur? Maybe there is some control flow I'm not following,  but what your suggesting was my first intuition as well which is what this commit looks like: 

https://github.com/clj-kondo/clj-kondo/pull/1356/commits/cbe7e1561717f4526d4bfcca037ce8ee7da970aa. 
(though you need the fix from the next commit to run it)

It fails on this case which I hope highlights the issue, ill try to explain what I think you suggesting and why it didn't work for me.  

```clojure
(def foo ;; pre-walk: insert atom
    [s]
    (loop [a 1] ;; pre-walk: insert atom. post-walk:  atom should be in what state?
      (if true
        (recur 1) ;; set atom to true
        (loop [a 1] ;; Pre-walk: insert atom (overwrite our true value). post walk: atom is true, which is good, BUT what do we set the atom to now, we have lost track of if we have a loop and recur above?
          (if false
            (recur (a)) ;; set atom to true
            a)))))
```

But given your confidence that it isn't necessary, I must be missing something. Apologies for the long discussion.

**Comment by borkdude** [comment]
@drewverlee About the length of the discussion: no problem at all. I will try it out locally and try to see if I can detect any problems.

**Comment by borkdude** [comment]
@drewverlee I took a look at your code. The thing I would do differently is this: do not re-use the atom previously inserted when you encounter a new loop or fn. Always insert a new one. So when recur is encountered that matches that loop or fn, it will pick up on that one. Unless there was an inner fn or loop, then the recur would pick up on the inner fn / loop atom and as a result the outer loop / fn atom would not have been populated. That is how you detect that there was a missing recur for the outer loop / fn. The only thing you need is an atom with a boolean in it.

**Pull request closed without merging**
