### PR TITLE
Consider cljd files as source files

### LINKED ISSUE #2105: .cljd files are not analyzed when linting a folder
[ To keep development of this project going, consider sponsoring. If you are
already a sponsor, thank you! ]

**version**

master

**platform**

JVM

**editor**

also happens with lsp

**problem**

clj-kondo doesn't consider .cljd files when linting a `src` folder

**repro**

`git clone https://github.com/wkok/hello.git`
`clj-kondo --lint src`

**expected behavior**

Lint at least like .clj files

PR coming

### PR DESCRIPTION
**Pull request by ericdallo**
Please answer the following questions and leave the below in as part of your PR.

- [X] I have read the [developer documentation](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md).

- [X] This PR corresponds to an [issue with a clear problem statement](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).

- [X] This PR contains a [test](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md#tests) to prevent against future regressions

- [X] I have updated the [CHANGELOG.md](https://github.com/clj-kondo/clj-kondo/blob/master/CHANGELOG.md) file with a description of the addressed issue.

Fixes #2105

### CODE REVIEW

**Comment by borkdude** [comment]
What is the `:lang` in the findings for this example?

**Comment by borkdude** [comment]
Anyway I'll just merge, this is a good start, we can improve later.

**Comment by ericdallo** [comment]
It's the default lang (:clj)

**Comment by borkdude** [comment]
I think syntactically .cljd is closer to .cljs than .clj with the string requires, etc so maybe temporarily setting that is better, but we should probably have a custom `:cljd` thing.

**Pull request merged**
