### PR TITLE
Update tools-deps linter to match latest CLI release

### PR DESCRIPTION
**Pull request by dpassen**
Addresses issue #1318

### CODE REVIEW

**Comment by borkdude** [comment]
@seancorfield @puredanger Would you mind double-checking this PR regarding the newest "rules" around the combinations of keys for gitlibs in deps.edn?

**Comment by puredanger** [comment]
Looks ok to me

**Comment by borkdude** [comment]
@dpassen Could you not use force-pushes for PRs for clj-kondo? It's hard for me to follow what changed in the meantime.

**Comment by dpassen** [comment]
Sorry, was just rebasing on top of master. I won't do it again.

**Comment by borkdude** [comment]
@dpassen No worries, I squash commits through Github's "squash and merge" feature.

**Comment by borkdude** [comment]
I think we could do additional validation on the library symbol, in case it's a github thing some other rules might apply, but we can do that in an additional PR. At least the false positives are fixed, thanks a lot @dpassen !

**Pull request merged**
