### PR TITLE
unit tests: explore using matcher-combinators lib

### LINKED ISSUE #1869: unit tests: consider using nubank/matcher-combinators
## Currently
Clj-kondo unit tests need to validate that large structures (or subsets thereof) contain expected values.
It currently uses internal fns like `assert-submap` to do this.

This is fine, but when expectations do not match actual returns, it can be difficult to pinpoint where the expectation was not met, especially for larger structures.

## Proposal
Do a baby-step experiment with [nubank/matcher-combinators](https://github.com/nubank/matcher-combinators).

I've used this library on other projects, and the things that absolutely delight me about it are:
- the ability to compare sub-portions of actual vs an expected result (we are already doing this)
- diff reporting between actual and expected results pinpoints the difference (we don't have this)

I'll start the experiment with [clj-kondo.analysis.java-test](https://github.com/clj-kondo/clj-kondo/blob/addcf68bbf0be511f5aaa1841d856ca2e9b2a39a/test/clj_kondo/analysis/java_test.clj#L1-L123).

## A taste
I'll contrive a failure in `clj-kondo.analysis.java-test/class-usages-test`.

### Today
Running just this test:
```Shell
$ clojure -M:test -v clj-kondo.analysis.java-test/class-usages-test
```

Currently produces the following error report:
```
Testing clj-kondo.analysis.java-test
=== class-usages-test

FAIL in (class-usages-test) (java_test.clj:73)
No superset of {:class "clojure.lang.Compiler", :uri #"file:.*corpus/java/usages.clj", :filename #"corpus/java/usages.clj", :row 8, :col 24, :end-row 9, :end-col 32, :import true} found
expected: (clojure.core/some (fn* [p1__17162__17166__auto__] (clj-kondo.test-utils/submap? m__17165__auto__ p1__17162__17166__auto__)) res__17164__auto__)
  actual: (not (clojure.core/some #object[clj_kondo.analysis.java_test$fn__20366$fn__20380$fn__20381 0x68bc3559 "clj_kondo.analysis.java_test$fn__20366$fn__20380$fn__20381@68bc3559"] [{:class "clojure.lang.PersistentVector", :uri "file:/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj", :filename "/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj", :row 1, :col 40, :end-row 1, :end-col 56, :import true} {:end-row 3, :name-end-col 22, :name-end-row 3, :name-row 3, :filename "/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj", :col 13, :class "java.lang.Exception", :name-col 13, :uri "file:/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj", :end-col 22, :row 3} {:end-row 4, :name-end-col 13, :name-end-row 4, :name-row 4, :filename "/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj", :col 1, :class "java.lang.Thread", :name-col 1, :uri "file:/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj", :end-col 13, :row 4} {:end-row 5, :name-end-col 14, :name-end-row 5, :name-row 5, :filename "/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj", :col 1, :class "java.lang.Thread", :name-col 2, :uri "file:/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj", :end-col 19, :row 5} {:end-row 6, :name-end-col 9, :name-end-row 6, :name-row 6, :filename "/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj", :col 2, :class "java.lang.Thread", :name-col 2, :uri "file:/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj", :end-col 9, :row 6} {:end-row 7, :name-end-col 17, :name-end-row 7, :name-row 7, :filename "/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj", :col 1, :class "clojure.lang.PersistentVector", :name-col 1, :uri "file:/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj", :end-col 17, :row 7} {:class "clojure.lang.Compiler", :uri "file:/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj", :filename "/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj", :row 9, :col 24, :end-row 9, :end-col 32, :import true} {:end-row 10, :name-end-col 18, :name-end-row 10, :name-row 10, :filename "/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj", :col 1, :class "clojure.lang.Compiler", :name-col 1, :uri "file:/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj", :end-col 18, :row 10} {:class "foo.bar.Baz", :uri "file:/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj", :filename "/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj", :row 11, :col 1, :end-row 11, :end-col 12} {:class "foo.bar.Baz", :uri "file:/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj", :filename "/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj", :row 12, :col 1, :end-row 12, :end-col 18} {:class "java.util.Date", :uri "file:/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj", :filename "/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj", :row 13, :col 1, :end-row 13, :end-col 15} {:end-row 14, :name-end-col 29, :name-end-row 14, :name-row 14, :filename "/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj", :col 1, :class "java.io.File", :name-col 2, :uri "file:/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj", :end-col 42, :row 14}]))
```

### With matcher-combinators

Test failure for the same run is reported as:
```
FAIL in (class-usages-test) (java_test.clj:73)
expected: (match? [{:class "clojure.lang.PersistentVector", :uri #"file:.*corpus/java/usages.clj", :filename #"corpus/java/usages.clj", :row 1, :col 40, :end-row 1, :end-col 56, :import true} {:end-row 3, :name-end-col 22, :name-end-row 3, :name-row 3, :filename #"corpus/java/usages.clj", :col 13, :class "java.lang.Exception", :name-col 13, :uri #"file:.*corpus/java/usages.clj", :end-col 22, :row 3} {:end-row 4, :name-end-col 13, :name-end-row 4, :name-row 4, :filename #"corpus/java/usages.clj", :col 1, :class "java.lang.Thread", :name-col 1, :uri #"file:.*corpus/java/usages.clj", :end-col 13, :row 4} {:end-row 5, :name-end-col 14, :name-end-row 5, :name-row 5, :filename #"corpus/java/usages.clj", :col 1, :class "java.lang.Thread", :name-col 2, :uri #"file:.*corpus/java/usages.clj", :end-col 19, :row 5} {:end-row 6, :name-end-col 9, :name-end-row 6, :name-row 6, :filename #"corpus/java/usages.clj", :col 2, :class "java.lang.Thread", :name-col 2, :uri #"file:.*corpus/java/usages.clj", :end-col 9, :row 6} {:end-row 7, :name-end-col 17, :name-end-row 7, :name-row 7, :filename #"corpus/java/usages.clj", :col 1, :class "clojure.lang.PersistentVector", :name-col 1, :uri #"file:.*corpus/java/usages.clj", :end-col 17, :row 7} {:class "clojure.lang.Compiler", :uri #"file:.*corpus/java/usages.clj", :filename #"corpus/java/usages.clj", :row 8, :col 24, :end-row 9, :end-col 32, :import true} {:end-row 10, :name-end-col 18, :name-end-row 10, :name-row 10, :filename #"corpus/java/usages.clj", :col 1, :class "clojure.lang.Compiler", :name-col 1, :uri #"file:.*corpus/java/usages.clj", :end-col 18, :row 10} {:class "foo.bar.Baz", :uri #"file:.*corpus/java/usages.clj", :filename #"corpus/java/usages.clj", :row 11, :col 1, :end-row 11, :end-col 12} {:class "foo.bar.Baz", :uri #"file:.*corpus/java/usages.clj", :filename #"corpus/java/usages.clj", :row 12, :col 1, :end-row 12, :end-col 18} {:class "java.util.Date", :uri #"file:.*corpus/java/usages.clj", :filename #"corpus/java/usages.clj", :row 13, :col 1, :end-row 13, :end-col 15} {:end-row 14, :name-end-col 29, :name-end-row 14, :name-row 14, :filename #"corpus/java/usages.clj", :col 1, :class "java.io.File", :name-col 2, :uri #"file:.*corpus/java/usages.clj", :end-col 42, :row 14}] java-class-usages)
  actual: [{:class "clojure.lang.PersistentVector",
  :uri
  "file:/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj",
  :filename
  "/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj",
  :row 1,
  :col 40,
  :end-row 1,
  :end-col 56,
  :import true}
 {:end-row 3,
  :name-end-col 22,
  :name-end-row 3,
  :name-row 3,
  :filename
  "/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj",
  :col 13,
  :class "java.lang.Exception",
  :name-col 13,
  :uri
  "file:/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj",
  :end-col 22,
  :row 3}
 {:end-row 4,
  :name-end-col 13,
  :name-end-row 4,
  :name-row 4,
  :filename
  "/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj",
  :col 1,
  :class "java.lang.Thread",
  :name-col 1,
  :uri
  "file:/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj",
  :end-col 13,
  :row 4}
 {:end-row 5,
  :name-end-col 14,
  :name-end-row 5,
  :name-row 5,
  :filename
  "/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj",
  :col 1,
  :class "java.lang.Thread",
  :name-col 2,
  :uri
  "file:/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj",
  :end-col 19,
  :row 5}
 {:end-row 6,
  :name-end-col 9,
  :name-end-row 6,
  :name-row 6,
  :filename
  "/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj",
  :col 2,
  :class "java.lang.Thread",
  :name-col 2,
  :uri
  "file:/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj",
  :end-col 9,
  :row 6}
 {:end-row 7,
  :name-end-col 17,
  :name-end-row 7,
  :name-row 7,
  :filename
  "/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj",
  :col 1,
  :class "clojure.lang.PersistentVector",
  :name-col 1,
  :uri
  "file:/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj",
  :end-col 17,
  :row 7}
 {:class "clojure.lang.Compiler",
  :uri
  "file:/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj",
  :filename "corpus/java/usages.clj",
  :row (mismatch (expected 8) (actual 9)),
  :col 24,
  :end-row 9,
  :end-col 32,
  :import true}
 {:end-row 10,
  :name-end-col 18,
  :name-end-row 10,
  :name-row 10,
  :filename
  "/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj",
  :col 1,
  :class "clojure.lang.Compiler",
  :name-col 1,
  :uri
  "file:/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj",
  :end-col 18,
  :row 10}
 {:class "foo.bar.Baz",
  :uri
  "file:/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj",
  :filename
  "/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj",
  :row 11,
  :col 1,
  :end-row 11,
  :end-col 12}
 {:class "foo.bar.Baz",
  :uri
  "file:/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj",
  :filename
  "/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj",
  :row 12,
  :col 1,
  :end-row 12,
  :end-col 18}
 {:class "java.util.Date",
  :uri
  "file:/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj",
  :filename
  "/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj",
  :row 13,
  :col 1,
  :end-row 13,
  :end-col 15}
 {:end-row 14,
  :name-end-col 29,
  :name-end-row 14,
  :name-row 14,
  :filename
  "/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj",
  :col 1,
  :class "java.io.File",
  :name-col 2,
  :uri
  "file:/home/lee/proj/oss/borkdude/clj-kondo/corpus/java/usages.clj",
  :end-col 42,
  :row 14}]

```

Here's a screenshot of a subset of the above to show the failure being highlighted:

image

## Checklist
Should work nicely from 
1. command line
   1. clojure test launch
   2. lein test launch
2. repl (I'll test in emacs)

## Concerns
We'll have to be careful to understand what current clj-kondo fns like `assert-submap` are doing.
I know that matcher-combinators already has regex matching support, but I'll have to check feature parity for other things we are doing internally.

## Alternatives
1. do nothing, stick with what we are doing now
2. write our own better diff reporter on failure
3. incorporate some other diff reporter (like [deep-diff2](https://github.com/lambdaisland/deep-diff2) for example - I do find syntax highlighting can make it harder to see diff highlighting for this lib's output)

## Next Steps
Already chatted with @borkdude on Slack about this, so we are a go for at least an experiment.
I'll follow up with a trial and if that works out, a PR.

### PR DESCRIPTION
**Pull request by lread**
Of note:
- experiment currently limited to clj-kondo.analysis.java-test ns
- updated .clj-kondo/config.edn to ignore matcher-combinators' match? assert expr

Closes #1869

Please answer the following questions and leave the below in as part of your PR.

- [x] I have read the [developer documentation](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md).

- [x] This PR corresponds to an [issue with a clear problem statement](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).

- [x] This PR contains a [test](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md#tests) to prevent against future regressions

- [ ] I have updated the [CHANGELOG.md](https://github.com/clj-kondo/clj-kondo/blob/master/CHANGELOG.md) file with a description of the addressed issue.

### CODE REVIEW

**Comment by lread** [comment]
I'm not doing anything around [normalizing files](https://github.com/clj-kondo/clj-kondo/blob/addcf68bbf0be511f5aaa1841d856ca2e9b2a39a/test/clj_kondo/test_utils.clj#L41-L46) yet.

I'll see what I can do there.

**Comment by borkdude** [comment]
@lread We could normalize before doing the match

**Comment by borkdude** [comment]
@lread I already like this a lot!

Screenshot 2022-11-08 at 10 41 32

**Comment by lread** [comment]
Glad you like it too @borkdude.

One thing I forgot to try out is a missing map from a vector of maps.
(Clj-kondo's current approach is to diff the count of elements and report on that, that's ok, but doesn't tell you a ton).
Some differs to a better job of this than others.  I'll try that out and report back in the issue.

> We could normalize before doing the match

Yeah, after taking a cursory peek at extending matcher-combinators, I think that some custom pre-processing would be the simplest to implement. I might still compare a pre-processing approach with a matcher-combinators extension (if I can figure out something that seems reasonable here).

**Comment by lread** [comment]
Note: normally I would like to first test locally on a Windows VM, but my Windows VM is currently a gong-show. So I'm letting CI do the Windows testing.

**Comment by lread** [comment]
@borkdude, lemme know what you think, am happy to adjust if needed/wanted.

**Comment by borkdude** [comment]
LGTM!

**Comment by borkdude** [comment]
Should I merge?

**Pull request merged**
