### PR TITLE
Fixes #1232 introduce report-duplicates linter config

### LINKED ISSUE #1232: Optionally report duplicates
**Is your feature request related to a problem? Please describe.**
In clojure-lsp it's possible to edit a file to produce many unresolved-var or unresolved-symbol lints, but the current behaviour is to only report the first occurence and swallow to subsequent ones. So a user has to find errors, fix the first one then find errors again, then fix the next etc... Many editors provide good support to navigate to all your diagnostics and this behavior neuters this functionality.

**Describe the solution you'd like**
Spoke with @borkdude, we'd like to add a config flag on each affected linter `report-duplicates` that when nil (default) or otherwise non-truthy would maintain the existing behaviour and when truthy would return all of the lint occurrences.

**Describe alternatives you've considered**
Talked about top level configuration for the desired behaviour but since most linters already report duplicates this seems like a nice, specific solution that can be extended anywhere ignoring duplicates is introduced later.

PR incoming

### PR DESCRIPTION
**Pull request by snoe**
Addresses #1232

### CODE REVIEW

**Comment by borkdude** [comment]
Looks good.

Maybe pull `(fnil conj [])` to a top-level function (I usually call it `(def vconj (fnil conj []))`) to avoid creating it on every call? I'm not sure if that helps, but I usually do that anyway.

Other thing: I think `unresolved-namespace` also doesn't report duplicates.

**Comment by borkdude** [comment]
@snoe Just to make sure this isn't lingering: I'm waiting for you to update the `:unresolved-namespace` linter with the same option. No hurry, just making sure you didn't miss it.

**Comment by snoe** [comment]
Oh I think we got crossed wires, @borkdude https://github.com/clj-kondo/clj-kondo/blob/master/src/clj_kondo/impl/namespace.clj#L326 This code isn't using a map to dedupe like the other linters and where the doseq happens to pull them out it seems like it would report all of them.

**Comment by borkdude** [comment]
@snoe I'm seeing only one warning here:

Screenshot 2021-03-31 at 17 23 11

That is because we are saving unresolved namespaces in a set in analyzer/namespace.clj, line 348:

```
:unresolved-namespaces #{}
```

**Comment by snoe** [comment]
thanks for the pointer @borkdude - that kept going over my head.

**Pull request merged**
