### PR TITLE
[#1638] Test to catch lint regressions caused by re-frame analysis

### PR DESCRIPTION
**Pull request by benedekfazekas**
add https://github.com/athensresearch/athens cljs code snapshot as is
now to lint against

Please answer the following questions and leave the below in as part of your PR.

- [x] I have read the [developer documentation](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md).

- [x] This PR correponds to an [issue with a clear problem statement](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).

- [ ] I have updated the [CHANGELOG.md](https://github.com/clj-kondo/clj-kondo/blob/master/CHANGELOG.md) file with a description of the addressed issue.

### CODE REVIEW

**Comment by borkdude** [comment]
@benedekfazekas Thanks! Wow, it's a bit much! Maybe we could do this another way: check out the athens repo at a specific commit and then run the tests over that.

**Comment by borkdude** [comment]
@benedekfazekas We could just use tools.deps to define a dependency on athens and then lint their code maybe? This is already done in several places, e.g. check the analysis/java_test.

**Comment by benedekfazekas** [comment]
will check analysis/java_test out

**Comment by benedekfazekas** [comment]
maybe wrong but athens being an app (not a lib) I don't think it is on clojars or on maven central

**Pull request merged**
