### PR TITLE
Fix #2093: add arm64 docker image

### LINKED ISSUE #2093: multi-architecture docker image (arm64, amd64)
[ Leave this text in if you want to promote it. ]

To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

[ To keep development of this project going, consider sponsoring. If you are
already a sponsor, thank you! You can remove this message. ]

**Is your feature request related to a problem? Please describe.**
Since the introduction of Apple’s M1 mac, the number of readily available computer with arm64 architecture is growing.
While both macOS and docker are making provide some level of support for executing amd64 binaries, they are not foolproof, and are slower.

This will also help other projects, such as super-linter, that includes clj tools.

**Describe the solution you'd like**
Please consider generating multi-architecture docker image (https://docs.docker.com/build/building/multi-platform/, https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/)

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

[ Optional: if you are interested in doing a PR yourself, please leave a note. ]

### PR DESCRIPTION
**Pull request by harryzcy**
Please answer the following questions and leave the below in as part of your PR.

- [x] I have read the [Clojure etiquette](https://clojure.org/community/etiquette) and will respect it when communicating on this platform.

- [x] I have read the [developer documentation](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md).

- [x] This PR corresponds to an [issue with a clear problem statement](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).

- [x] This PR contains a [test](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md#tests) to prevent against future regressions

- [x] I have updated the [CHANGELOG.md](https://github.com/clj-kondo/clj-kondo/blob/master/CHANGELOG.md) file with a description of the addressed issue.

---

Provide a arm64 docker image during release. Closes #2093.

### CODE REVIEW

**Comment by borkdude** [comment]
Thanks. I'll have a look at this hopefully next week

**Comment by borkdude** [comment]
@harryzcy Thanks for this PR. 

With babashka we had similar scripts to build Docker images using buildx in bash. But because it was hard to maintain these scripts, @lispyclouds and @cap10morgan ported it to babashka:

https://github.com/babashka/babashka/blob/master/.circleci/script/docker.clj

I think that would be best here also so I don't have to maintain two very different setups. If you're willing to port this using the approach in the babashka repo, then I'm willing to accept the PR.

**Comment by borkdude** [comment]
@harryzcy It seems this PR is mostly in support of https://github.com/super-linter/super-linter/issues/5070. Does that issue need multi-architecture docker images or is it sufficient to just download the linux aarch64 binary? If so you could just run the clj-kondo install script on a aarch64 docker image as well:

```
curl -sLO https://raw.githubusercontent.com/clj-kondo/clj-kondo/master/script/install-clj-kondo
chmod +x install-clj-kondo
./install-clj-kondo
```

**Comment by harryzcy** [comment]
> I think that would be best here also so I don't have to maintain two very different setups. If you're willing to port this using the approach in the babashka repo, then I'm willing to accept the PR.

I'm not familiar with closure syntax. I'm not sure if I can.

> It seems this PR is mostly in support of https://github.com/super-linter/super-linter/issues/5070. Does that issue need multi-architecture docker images or is it sufficient to just download the linux aarch64 binary? If so you could just run the clj-kondo install script on a aarch64 docker image as well

I'm not the maintainer of super-linter. But I believe it's easier for them if there's a docker image available.
@ferrarimarco Can you take a look at this?

**Comment by borkdude** [comment]
> I'm not familiar with closure syntax. I'm not sure if I can.

I'll take it from here then.

**Comment by harryzcy** [comment]
> I'll take it from here then.

Thank you! @borkdude

**Comment by ferrarimarco** [comment]
> > It seems this PR is mostly in support of [super-linter/super-linter#5070](https://github.com/super-linter/super-linter/issues/5070). Does that issue need multi-architecture docker images or is it sufficient to just download the linux aarch64 binary? If so you could just run the clj-kondo install script on a aarch64 docker image as well
> 
> I'm not the maintainer of super-linter. But I believe it's easier for them if there's a docker image available. @ferrarimarco Can you take a look at this?

Hi folks! We currently pull `clj-kondo` from its container image:

https://github.com/super-linter/super-linter/blob/a3046b34e64efe25bfd02dbc729f52f0a3296f80/Dockerfile#L26

This allows us to keep the `clj-kondo` up to date using DependaBot, but we don't necessarily need an `arm64` container image.

(probably out of scope for this PR) I'm not familiar with the clj-kondo install script, but if we go that route, we likely need a way to install a fixed version of `clj-kondo` that we can keep up to date with DependaBot. We can get creative here, but let's not derail this thread too much :)

Thanks!

**Comment by borkdude** [comment]
The install script supports a `--version` flag

**Comment by borkdude** [comment]
I'll work on porting babashka's docker build to clj-kondo now. Hopefully done this week.

**Comment by borkdude** [comment]
Fixed on master. You can see the multi arch image here now:

https://hub.docker.com/layers/cljkondo/clj-kondo/2024.02.13-SNAPSHOT/images/sha256-ea849cf18ceec156ce35c17098aab0340beb5f5eaaa515392d8f56da3e3cd152?context=explore

Can you please test it out before I make a final release?

**Pull request closed without merging**
