### PR TITLE
Tests for #1474

### PR DESCRIPTION
**Pull request by hsartoris-bard**
- [X] I have read the [developer documentation](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md).

- [X] This PR correponds to an [issue with a clear problem statement](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).

Currently failing tests to demonstrate several forms of the issue outlined in #1474

### CODE REVIEW

**Comment by hsartoris-bard** [comment]
Probably obvious, but the fact that these passed on mac is potentially an issue

**Comment by borkdude** [comment]
Mac builds don't run in PRs to save some CircleCI credits. In fact, the linux-static build should also be disabled again.

**Comment by borkdude** [comment]
Sorry, I forgot to look at these tests and ended up using the examples from your issue directly. I'll take a look tomorrow why this test is still failing after making your PR up to date.

**Comment by hsartoris-bard** [comment]
Great; thanks for fixing this!

**Pull request merged**
