### PR TITLE
Avoid side-effects on `clj-kondo.impl.core` ns load

### PR DESCRIPTION
**Pull request by ericdallo**
This is more of a refactor to avoid loading a resource on ns load

### CODE REVIEW

**Comment by borkdude** [comment]
What problem does this solve?

**Comment by ericdallo** [comment]
I was refactoring clojure-lsp jar build and accidentally found that I missed to include some resources, then I found that clj-kondo does that on ns loading, so I thought would be nice to avoid side effects to io during ns load, no particular issue

**Comment by borkdude** [comment]
Doing this at ns load time helps with GraalVM, it's a compile time constant, so that you don't need to include it in your GraalVM resource configuration. As such, I suspect this would be a breaking change. You can test this by compiling this locally and then doing `clj-kondo --version` which I think won't print the right version anymore. Since this doesn't really solve a problem, but introduces one, I think it's better to close this PR. The PR template is there for a reason.

**Comment by ericdallo** [comment]
No problem, feel free to close it

**Pull request closed without merging**
