### PR TITLE
False positive `:def-fn` on `def` + `reify`

### PR DESCRIPTION
**Pull request by sumbach**
Please answer the following questions and leave the below in as part of your PR.

- [x] I have read the [developer documentation](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md).

- [ ] This PR corresponds to an [issue with a clear problem statement](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).
    - I mentioned this issue at https://github.com/clj-kondo/clj-kondo/issues/1920#issuecomment-1474551676 but haven't opened a separate GH issue for it

- [x] This PR contains a [test](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md#tests) to prevent against future regressions

- [x] I have updated the [CHANGELOG.md](https://github.com/clj-kondo/clj-kondo/blob/master/CHANGELOG.md) file with a description of the addressed issue.

### CODE REVIEW

**Comment by sumbach** [comment]
@borkdude I took a quick attempt at writing a failing test demonstrating the issue. I could definitely use your input on how to _resolve_ the issue, though 😉 

I think I see the cause:

* `reify` form is ultimately run through `analyze-fn`: https://github.com/clj-kondo/clj-kondo/blob/f1b13914ee192953f1ef/src/clj_kondo/impl/analyzer.clj#L1442-L1444
* `analyze-fn` reports `:def-fn` finding if parents of current form are `def` or `def` + `let`: https://github.com/clj-kondo/clj-kondo/blob/f1b13914ee192953f1ef/src/clj_kondo/impl/analyzer.clj#L931-L933

One approach I can think of is to add a check to `def-fn?` to ensure that the current form is, in fact, `fn`. This could take the form of an allow list including:

* `[clojure.core fn]` / `[cljs.core fn]`
* `[clojure.core fn*]` / `[cljs.core fn*]`
* `[schema.core fn]` (maybe?)
* `[clojure.core bound-fn]` (maybe?)

Or a block list of forms to exclude:

* `[clojure.core reify]` / `[cljs.core reify]`
* `[cljs.core specify!]` (didn't know about this one until today 😬 )

NOTE: The block list approach might still report `:def-fn` findings on weird stuff like `defmethod`, `deftype`, `extend-protocol`, `extend-type` within `def` -- I don't think any of these would be useful and probably shouldn't occur within normal code.

Do you have any concerns with this approach? Any preference on allow list vs block list? Any other alternatives to consider?

**Comment by borkdude** [comment]
Yes, I think the allow list sounds good, just include core fn and see if any tests with :def-fn are breaking and change accordingly.

**Comment by sumbach** [comment]
Thanks for the instant feedback @borkdude ! 😀 

I tried both the block list and the allow list (on separate commits within this PR).

I was initially convinced the allow list was better (since it should eliminate all false positives, known and unknown). But there's only one known false positive, `reify`, and quite a few different fn-ish forms that clj-kondo treats as fn. With the allow list, we would need to be vigilant about adding any new fn-ish forms to the `fn-form?` predicate.

For example, should `fn-form?` include `[day8.re-frame.tracing fn-traced]`?

**Comment by borkdude** [comment]
Thinking more about it, I think adding an extra callstack element is better. I pushed this to master now and together with your PR (test + changelogs) this will be the full solution. Can you update your PR?

**Comment by sumbach** [comment]
Yes! The extra element in callstack looks like an excellent solution to me as well.

I've pushed some updates to the branch, including tests for `{:lint-as {some.ns/my-fn clojure.core/fn}}` and `{:lint-as {some.ns/my-reify clojure.core/reify}}`.

Please let me know you want the git history cleaned up. I'm happy to rebase/squash/etc, but wanted to check with you before doing a force push.

Thanks!!!

**Comment by borkdude** [comment]
Thanks!

**Pull request merged**
