### PR TITLE
Add redundant-nesting linter

### LINKED ISSUE #2212: Linter for redundant nesting
To upvote this issue, give it a thumbs up. See [this list](https://github.com/clj-kondo/clj-kondo/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) for the most upvoted issues.

**Is your feature request related to a problem? Please describe.**
Nesting certain variadic functions/macros is redundant, and is usually confusing. We could catch this quite easily. E.g:
```clojure
(min 5 2 (min 3 7))
;; => 2
(min 5 2 3 7)
;; => 2

(* 3 4 (* 5 6))
;; => 360
(* 3 4 5 6)
;; => 360

(str "foo" "bar" (str "baz" "qux"))
;; => "foobarbazqux"
(str "foo" "bar" "baz" "qux")
;; => "foobarbazqux"

(concat [1 2] [3 4] (concat [5 6] [7 8]))
;; => (1 2 3 4 5 6 7 8)
(concat [1 2] [3 4] [5 6] [7 8])
;; => (1 2 3 4 5 6 7 8)
```

**Describe the solution you'd like**
When one of these functions/macros is nested within itself, raise a warning.

**Additional context**
From a cursory browse of clojure.core, this is a list of functions which could be included:
`*` `*'` `+` `+'` `and` `comp` `concat` `every-pred` `lazy-cat` `max` `merge` `min` `or` `some-fn` `str`

The redundant `do` and `let` linters are already present, but I guess a similar idea. 

I knocked up the code for it here: https://github.com/tomdl89/clj-kondo/tree/redundant-nesting and can submit as a PR if there's interest.

### PR DESCRIPTION
**Pull request by tomdl89**
Fixes #2212 

Worth reading by commit, as I split out the tests & self-lint fixes from the functional code

- [x] I have read the [Clojure etiquette](https://clojure.org/community/etiquette) and will respect it when communicating on this platform.

- [x] I have read the [developer documentation](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md).

- [x] This PR corresponds to an [issue with a clear problem statement](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).

- [x] This PR contains a [test](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md#tests) to prevent against future regressions

- [x] I have updated the [CHANGELOG.md](https://github.com/clj-kondo/clj-kondo/blob/master/CHANGELOG.md) file with a description of the addressed issue.

### CODE REVIEW

**Comment by borkdude** [comment]
@tomdl89 I would kindly like to ask you to avoid force pushing branches so I can follow the diffs easier.

See https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md#force-push

**Comment by borkdude** [comment]
I'm going to take a look at this Wednesday probably at the earliest, but I'm already running this branch locally. Note that force pushing also makes it harder to just do a `git pull` for me locally.

**Comment by tomdl89** [comment]
@borkdude is this PR ok to close? For future reference, does force pushed PR = not merged + code committed by you instead? Cheers

**Comment by borkdude** [comment]
@tomdl89 Yes, thanks . I just wanted to make a few minor tweaks and decided to do it myself rather than a back-and-forth. Thanks again!

**Comment by tomdl89** [comment]
Cool, sounds good. Thanks for getting it done 🚀

**Pull request closed without merging**
