### PR TITLE
Add docker pre-commit hook

### PR DESCRIPTION
**Pull request by allie-jo**
Please answer the following questions and leave the below in as part of your PR.

- [x] I have read the [developer documentation](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md).

- [x] This PR corresponds to an [issue with a clear problem statement](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md#start-with-an-issue-before-writing-code).
  - closes https://github.com/clj-kondo/clj-kondo/issues/1863

- [ ] This PR contains a [test](https://github.com/clj-kondo/clj-kondo/blob/master/doc/dev.md#tests) to prevent against future regressions
  - Don't believe there's tests for these build steps?

- [x] I have updated the [CHANGELOG.md](https://github.com/clj-kondo/clj-kondo/blob/master/CHANGELOG.md) file with a description of the addressed issue.

I've tested the hook and the template generation locally and it all seems to work as expected. I'm not super familiar with babashka tasks and their doesn't seem to be much documentation on the release process. Let me know if i missed anything!

### CODE REVIEW

**Comment by allie-jo** [comment]
12 minute PR turnaround. hot damn

**Comment by borkdude** [comment]
@allie-jo 🚀 I wonder if we should set the version to the latest release rather than the snapshot version though? Thoughts on this?

**Comment by allie-jo** [comment]
you're generally not supposed to set the `rev` tag to `master` in pre-commit-configs, just to tags, because the hook wont get updated (pre-commit will warn if you try to do this). so if i understand the release process for clj-kondo, the next time you release, it'll bump to to the non-snapshot version and then anyone that adds the hook would use that release tag for their `rev` which points to the the stable docker image version. If people are pointing their `rev` keys to tags like they're supposed too, they'll never interact with a `SNAPSHOT` version. 

So actually since their's no tag that contains the pre-commit-hooks file with the docker hook yet, the docker-hook will only work when pointing to `master` until you cut a new release :/

**Comment by borkdude** [comment]
We could manually change it to the previous release version for now?

**Comment by allie-jo** [comment]
sure! we could also remove it from the ci integration docs until you cut a release so people don't try to use it until their's a tag they can set it too.

**Comment by borkdude** [comment]
A PR which manually fixes the version seems sufficient I think

**Pull request merged**
